
const captions = [
  "This banana just got back from Basel.",
  "Conceptually ripe.",
  "Minimalism, but make it potassium.",
  "You wouldn’t peelieve it.",
  "Post-post-bananaism.",
  "Warhol weeps softly.",
  "Critics called it slippery yet bold.",
  "Somewhere in this banana lies meaning.",
  "Peel back the layers of late capitalism.",
  "Hanging by a thread of citrus satire.",
  "Dada, but edible.",
  "Fresh from the MoMA gift shop.",
  "A still life in absolute chaos.",
  "The banana stares back.",
  "Fruit-forward absurdism.",
  "Performance fruit, frozen in time.",
  "This one's Maurizio-approved.",
  "Cattelan did it first — I did it cheaper.",
  "Art Basel energy at grocery store prices.",
  "Certified conceptual produce.",
  "As seen in gallery gift shops (probably).",
  "Do not eat. This is serious.",
  "Banana, but make it meta.",
  "More duct tape, more meaning.",
  "An homage to the world’s most expensive snack.",
  "Maurizio Cattelan walked so this banana could slip.",
  "It’s not plagiarism — it’s parody.",
  "Inspired by a banana and a dream.",
  "Museum-quality fruit.",
  "Cattelan called, he wants his fruit back.",
  "An economy of fruit, an abundance of meaning.",
  "This piece was once taped to a wall. Spiritually.",
  "Funnier than the original — and cheaper too."
];
