
const captions = [
  "This banana just got back from Basel.",
  "Conceptually ripe.",
  "Minimalism, but make it potassium.",
  "You wouldn’t peelieve it.",
  "Post-post-bananaism.",
  "Warhol weeps softly.",
  "Critics called it slippery yet bold.",
  "Somewhere in this banana lies meaning.",
  "Peel back the layers of late capitalism.",
  "Hanging by a thread of citrus satire.",
  "Dada, but edible.",
  "Fresh from the MoMA gift shop.",
  "A still life in absolute chaos.",
  "The banana stares back.",
  "Fruit-forward absurdism.",
  "Performance fruit, frozen in time.",
  "This one's Cattelan-approved.",
  "The spirit of Cattelan haunts this peel.",
  "Art Basel energy at grocery store prices.",
  "Certified conceptual produce.",
  "Do not eat. This is serious.",
  "Banana, but make it meta.",
  "More duct tape, more meaning.",
  "An homage to the world’s most expensive snack.",
  "Cattelan walked so this banana could slip.",
  "It’s not plagiarism — it’s parody.",
  "Inspired by a banana and a dream.",
  "Museum-quality fruit.",
  "Cattelan called, he wants his fruit back.",
  "An economy of fruit, an abundance of meaning.",
  "This piece was once taped to a wall. Spiritually.",
  "Funnier than the original — and cheaper too.",
  "Is this fruit, or just late-stage irony?",
  "The banana is a metaphor. You decide for what.",
  "May contain ideas, potassium, and provocation.",
  "Banana art is the new crypto.",
  "Unpeeling the artistic condition.",
  "Abstracted, absurd, and a little bruised.",
  "Your daily dose of edible postmodernism.",
  "Free-range banana performance.",
  "No tape, just pure existential fruit.",
  "The fruit loopiest statement yet.",
  "Peel performance: day 1,247.",
  "It’s banana-adjacent expressionism.",
  "This fruit went to art school.",
  "Part of the duct tape diaspora.",
  "Fruit with gallery aspirations.",
  "Tropically conceptual.",
  "If Magritte ate potassium.",
  "The banana gazes also.",
  "It fell off the pedestal and onto the floor.",
  "Curated chaos with a side of fruit.",
  "Like a poem, but peelier.",
  "Still more nutritious than some NFTs.",
  "Less sticky than the original, equally strange.",
  "Duct tape sold separately.",
  "Don’t think too hard, it’s just fruit.",
  "A bruised commentary on modern value.",
  "Banana, curated.",
  "No bananas were harmed in the making of this caption.",
  "Gallery-goers hate it. Fruit lovers love it.",
  "It belongs in a fridge. Or a museum. Or both.",
  "The Duchamp of the produce aisle.",
  "Just enough potassium to challenge the system.",
  "Peel-based provocation.",
  "Not art? Says who?",
  "This caption was hand-peeled.",
  "Banana noir with post-ironic tones.",
  "Duct-tape dreams deferred.",
  "One banana. Infinite interpretations."
];
